// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System_Web_App.Models;

public partial class Choice
{
    public int q_id { get; set; }

    public int ch_no { get; set; }

    public string ch_text { get; set; }

    public virtual Question q_idNavigation { get; set; }
}