// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System_Web_App.Models;

public partial class Department
{
    public int dept_no { get; set; }

    public string dept_name { get; set; }

    public int? sup_id { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    public virtual ICollection<Works_in> Works_ins { get; set; } = new List<Works_in>();

    public virtual Instructor sup { get; set; }

    public virtual ICollection<Course> crs { get; set; } = new List<Course>();
}