// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System_Web_App.Models;

public partial class Department
{
    public int dept_no { get; set; }

    public string dept_name { get; set; }

    public int? sup_id { get; set; }

    public virtual ICollection<Dept_inst_course> Dept_inst_courses { get; set; } = new List<Dept_inst_course>();

    public virtual ICollection<Exam> Exams { get; set; } = new List<Exam>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    public virtual Instructor sup { get; set; }
}