// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Examination_System_Web_App.Models;

public partial class ExamSysContext : DbContext
{
    public ExamSysContext()
    {
    }

    public ExamSysContext(DbContextOptions<ExamSysContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Choice> Choices { get; set; }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<Dept_inst_course> Dept_inst_courses { get; set; }

    public virtual DbSet<Exam> Exams { get; set; }

    public virtual DbSet<Instructor> Instructors { get; set; }

    public virtual DbSet<Question> Questions { get; set; }

    public virtual DbSet<Std_course> Std_courses { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<Student_answer> Student_answers { get; set; }

    public virtual DbSet<Topic> Topics { get; set; }
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<Role> Roles { get; set; }  

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=tcp:pdsqlproject.database.windows.net,1433;Initial Catalog=ExamSys;User ID=sqladmin@pdsqlproject;Password=Adminpass_123");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {

        modelBuilder.Entity<Choice>(entity =>
        {
            entity.HasKey(e => new { e.q_id, e.ch_no }).HasName("pk_choice");

            entity.ToTable("Choice");

            entity.Property(e => e.ch_text).IsUnicode(false);

            entity.HasOne(d => d.q_idNavigation).WithMany(p => p.Choices)
                .HasForeignKey(d => d.q_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Choice__q_id__08B54D69");
        });

        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasKey(e => e.crs_id).HasName("PK__Course__ECAF5375F84ABB33");

            entity.ToTable("Course");

            entity.Property(e => e.crs_name)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Department>(entity =>
        {
            entity.HasKey(e => e.dept_no).HasName("PK__Departme__DCA63FA6C64B0777");

            entity.ToTable("Department");

            entity.Property(e => e.dept_name)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.sup).WithMany(p => p.Departments)
                .HasForeignKey(d => d.sup_id)
                .HasConstraintName("fk_department");
        });

        modelBuilder.Entity<Dept_inst_course>(entity =>
        {
            entity.HasKey(e => new { e.dept_no, e.inst_id, e.crs_id }).HasName("pk_Dept_inst_course");

            entity.ToTable("Dept_inst_course");

            entity.HasOne(d => d.crs).WithMany(p => p.Dept_inst_courses)
                .HasForeignKey(d => d.crs_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Dept_inst__crs_i__10E07F16");

            entity.HasOne(d => d.dept_noNavigation).WithMany(p => p.Dept_inst_courses)
                .HasForeignKey(d => d.dept_no)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Dept_inst__dept___0EF836A4");

            entity.HasOne(d => d.inst).WithMany(p => p.Dept_inst_courses)
                .HasForeignKey(d => d.inst_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Dept_inst__inst___0FEC5ADD");
        });

        modelBuilder.Entity<Exam>(entity =>
        {
            entity.HasKey(e => e.exam_id).HasName("PK__Exam__9C8C7BE988183B29");

            entity.ToTable("Exam");

            entity.Property(e => e.exam_date).HasColumnType("datetime");
            entity.Property(e => e.exam_duration).HasDefaultValue(120);
            entity.Property(e => e.exam_name)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.crs).WithMany(p => p.Exams)
                .HasForeignKey(d => d.crs_id)
                .HasConstraintName("FK__Exam__crs_id__778AC167");

            entity.HasOne(d => d.dept_noNavigation).WithMany(p => p.Exams)
                .HasForeignKey(d => d.dept_no)
                .HasConstraintName("FK__Exam__dept_no__0C1BC9F9");
        });

        modelBuilder.Entity<Instructor>(entity =>
        {
            entity.HasKey(e => e.ins_id).HasName("PK__Instruct__9CB72D209C1FBDC1");

            entity.ToTable("Instructor");

            entity.Property(e => e.ins_email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ins_fname)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ins_gender)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.ins_lname)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.ins_password)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Question>(entity =>
        {
            entity.HasKey(e => e.q_id).HasName("PK__Question__3D59B310821E6021");

            entity.ToTable("Question");

            entity.Property(e => e.q_text).IsUnicode(false);
            entity.Property(e => e.q_type)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.crs).WithMany(p => p.Questions)
                .HasForeignKey(d => d.crs_id)
                .HasConstraintName("FK__Question__crs_id__7A672E12");
        });

        modelBuilder.Entity<Std_course>(entity =>
        {
            entity.HasKey(e => new { e.std_id, e.crs_id }).HasName("pk_std_course");

            entity.ToTable("Std_course");

            entity.Property(e => e.status)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.crs).WithMany(p => p.Std_courses)
                .HasForeignKey(d => d.crs_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_std_course_crs_id");

            entity.HasOne(d => d.std).WithMany(p => p.Std_courses)
                .HasForeignKey(d => d.std_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_std_course_std_id");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.std_id).HasName("PK__Student__0B0245BAE0334036");

            entity.ToTable("Student");

            entity.HasIndex(e => e.std_email, "cons").IsUnique();

            entity.Property(e => e.std_email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.std_fname)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.std_gender)
                .HasMaxLength(1)
                .IsUnicode(false);
            entity.Property(e => e.std_lname)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.std_password)
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.dept_noNavigation).WithMany(p => p.Students)
                .HasForeignKey(d => d.dept_no)
                .HasConstraintName("FK__Student__dept_no__6A30C649");
        });

        modelBuilder.Entity<Student_answer>(entity =>
        {
            entity.HasKey(e => new { e.std_id, e.exam_id, e.q_id });

            entity.ToTable("Student_answer");

            entity.HasOne(d => d.exam).WithMany(p => p.Student_answers)
                .HasForeignKey(d => d.exam_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Student_a__exam___04E4BC85");

            entity.HasOne(d => d.q_idNavigation).WithMany(p => p.Student_answers)
                .HasForeignKey(d => d.q_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Student_an__q_id__05D8E0BE");

            entity.HasOne(d => d.std).WithMany(p => p.Student_answers)
                .HasForeignKey(d => d.std_id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Student_a__std_i__03F0984C");
        });

        modelBuilder.Entity<Topic>(entity =>
        {
            entity.HasKey(e => e.top_id).HasName("PK__Topic__B582A63D45B68EB7");

            entity.ToTable("Topic");

            entity.Property(e => e.top_name)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.crs).WithMany(p => p.Topics)
                .HasForeignKey(d => d.crs_id)
                .HasConstraintName("FK__Topic__crs_id__6754599E");
        });
        modelBuilder.Entity<Role>(r =>
        {
            r.HasData(new List<Role>()
            {
                new Role() { Id = 1, RoleName = "Admin" },
                new Role() { Id = 2, RoleName = "Instructor" },
                new Role() { Id = 3, RoleName = "Student" }
            });
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}