// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System_Web_App.Models;

public partial class Instructor
{
    public int ins_id { get; set; }

    public string ins_fname { get; set; }

    public string ins_lname { get; set; }

    public string ins_email { get; set; }

    public string ins_password { get; set; }

    public int? ins_age { get; set; }

    public string ins_gender { get; set; }

    public int? ins_salary { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual ICollection<Dept_inst_course> Dept_inst_courses { get; set; } = new List<Dept_inst_course>();
}