// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System_Web_App.Models;

public partial class Question
{
    public int q_id { get; set; }

    public string q_text { get; set; }

    public string q_type { get; set; }

    public int? q_modalanswer { get; set; }

    public int? q_score { get; set; }

    public int? crs_id { get; set; }

    public virtual ICollection<Choice> Choices { get; set; } = new List<Choice>();

    public virtual ICollection<Student_answer> Student_answers { get; set; } = new List<Student_answer>();

    public virtual Course crs { get; set; }
}