// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Examination_System_Web_App.Models;

public partial class Student
{
    public int std_id { get; set; }

    public string std_fname { get; set; }

    public string std_lname { get; set; }

    public string std_email { get; set; }

    public string std_password { get; set; }

    public int? std_age { get; set; }

    public string std_gender { get; set; }

    public int? dept_no { get; set; }
    
    public virtual ICollection<Std_course> Std_courses { get; set; } = new List<Std_course>();
   
    public virtual ICollection<Student_answer> Student_answers { get; set; } = new List<Student_answer>();
    
    public virtual Department dept_noNavigation { get; set; }
}