// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System_Web_App.Models;

public partial class Student_answer
{
    public int std_id { get; set; }

    public int exam_id { get; set; }

    public int q_id { get; set; }

    public int? answer { get; set; }

    public int? ans_score { get; set; }

    public virtual Exam exam { get; set; }

    public virtual Question q_idNavigation { get; set; }

    public virtual Student std { get; set; }
}