// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System_Web_App.Models;

public partial class Topic
{
    public int top_id { get; set; }

    public string top_name { get; set; }

    public int? crs_id { get; set; }

    public virtual Course crs { get; set; }
}