// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System_Web_App.Models;

public partial class Works_in
{
    public int ins_id { get; set; }

    public int branch_no { get; set; }

    public int dept_no { get; set; }

    public virtual Branch branch_noNavigation { get; set; }

    public virtual Department dept_noNavigation { get; set; }

    public virtual Instructor ins { get; set; }
}