// <auto-generated />
using System;
using Examination_System_Web_App.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Examination_System_Web_App.Migrations
{
    [DbContext(typeof(ExamSysContext))]
    [Migration("20240322013620_UserRoles")]
    partial class UserRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Examination_System_Web_App.Models.Choice", b =>
                {
                    b.Property<int>("q_id")
                        .HasColumnType("int");

                    b.Property<int>("ch_no")
                        .HasColumnType("int");

                    b.Property<string>("ch_text")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("q_id", "ch_no")
                        .HasName("pk_choice");

                    b.ToTable("Choice", (string)null);
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Course", b =>
                {
                    b.Property<int>("crs_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("crs_id"));

                    b.Property<int?>("crs_duration")
                        .HasColumnType("int");

                    b.Property<string>("crs_name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("crs_id")
                        .HasName("PK__Course__ECAF5375F84ABB33");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Department", b =>
                {
                    b.Property<int>("dept_no")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dept_no"));

                    b.Property<string>("dept_name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("sup_id")
                        .HasColumnType("int");

                    b.HasKey("dept_no")
                        .HasName("PK__Departme__DCA63FA6C64B0777");

                    b.HasIndex("sup_id");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Dept_inst_course", b =>
                {
                    b.Property<int>("dept_no")
                        .HasColumnType("int");

                    b.Property<int>("inst_id")
                        .HasColumnType("int");

                    b.Property<int>("crs_id")
                        .HasColumnType("int");

                    b.HasKey("dept_no", "inst_id", "crs_id")
                        .HasName("pk_Dept_inst_course");

                    b.HasIndex("crs_id");

                    b.HasIndex("inst_id");

                    b.ToTable("Dept_inst_course", (string)null);
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Exam", b =>
                {
                    b.Property<int>("exam_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("exam_id"));

                    b.Property<int?>("crs_id")
                        .HasColumnType("int");

                    b.Property<int?>("dept_no")
                        .HasColumnType("int");

                    b.Property<DateTime?>("exam_date")
                        .HasColumnType("datetime");

                    b.Property<int?>("exam_duration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(120);

                    b.Property<string>("exam_name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("exam_id")
                        .HasName("PK__Exam__9C8C7BE988183B29");

                    b.HasIndex("crs_id");

                    b.HasIndex("dept_no");

                    b.ToTable("Exam", (string)null);
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Instructor", b =>
                {
                    b.Property<int>("ins_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ins_id"));

                    b.Property<int?>("ins_age")
                        .HasColumnType("int");

                    b.Property<string>("ins_email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ins_fname")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ins_gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("ins_lname")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ins_password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ins_salary")
                        .HasColumnType("int");

                    b.HasKey("ins_id")
                        .HasName("PK__Instruct__9CB72D209C1FBDC1");

                    b.ToTable("Instructor", (string)null);
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Question", b =>
                {
                    b.Property<int>("q_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("q_id"));

                    b.Property<int?>("crs_id")
                        .HasColumnType("int");

                    b.Property<int?>("q_modalanswer")
                        .HasColumnType("int");

                    b.Property<int?>("q_score")
                        .HasColumnType("int");

                    b.Property<string>("q_text")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("q_type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("q_id")
                        .HasName("PK__Question__3D59B310821E6021");

                    b.HasIndex("crs_id");

                    b.ToTable("Question", (string)null);
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "Instructor"
                        },
                        new
                        {
                            Id = 3,
                            RoleName = "Student"
                        });
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Std_course", b =>
                {
                    b.Property<int>("std_id")
                        .HasColumnType("int");

                    b.Property<int>("crs_id")
                        .HasColumnType("int");

                    b.Property<int?>("grade")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("std_id", "crs_id")
                        .HasName("pk_std_course");

                    b.HasIndex("crs_id");

                    b.ToTable("Std_course", (string)null);
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Student", b =>
                {
                    b.Property<int>("std_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("std_id"));

                    b.Property<int?>("dept_no")
                        .HasColumnType("int");

                    b.Property<int?>("std_age")
                        .HasColumnType("int");

                    b.Property<string>("std_email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("std_fname")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("std_gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("std_lname")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("std_password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("std_id")
                        .HasName("PK__Student__0B0245BAE0334036");

                    b.HasIndex("dept_no");

                    b.HasIndex(new[] { "std_email" }, "cons")
                        .IsUnique()
                        .HasFilter("[std_email] IS NOT NULL");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Student_answer", b =>
                {
                    b.Property<int>("std_id")
                        .HasColumnType("int");

                    b.Property<int>("exam_id")
                        .HasColumnType("int");

                    b.Property<int>("q_id")
                        .HasColumnType("int");

                    b.Property<int?>("ans_score")
                        .HasColumnType("int");

                    b.Property<int?>("answer")
                        .HasColumnType("int");

                    b.HasKey("std_id", "exam_id", "q_id");

                    b.HasIndex("exam_id");

                    b.HasIndex("q_id");

                    b.ToTable("Student_answer", (string)null);
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Topic", b =>
                {
                    b.Property<int>("top_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("top_id"));

                    b.Property<int?>("crs_id")
                        .HasColumnType("int");

                    b.Property<string>("top_name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("top_id")
                        .HasName("PK__Topic__B582A63D45B68EB7");

                    b.HasIndex("crs_id");

                    b.ToTable("Topic", (string)null);
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("RoleUser");
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Choice", b =>
                {
                    b.HasOne("Examination_System_Web_App.Models.Question", "q_idNavigation")
                        .WithMany("Choices")
                        .HasForeignKey("q_id")
                        .IsRequired()
                        .HasConstraintName("FK__Choice__q_id__08B54D69");

                    b.Navigation("q_idNavigation");
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Department", b =>
                {
                    b.HasOne("Examination_System_Web_App.Models.Instructor", "sup")
                        .WithMany("Departments")
                        .HasForeignKey("sup_id")
                        .HasConstraintName("fk_department");

                    b.Navigation("sup");
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Dept_inst_course", b =>
                {
                    b.HasOne("Examination_System_Web_App.Models.Course", "crs")
                        .WithMany("Dept_inst_courses")
                        .HasForeignKey("crs_id")
                        .IsRequired()
                        .HasConstraintName("FK__Dept_inst__crs_i__10E07F16");

                    b.HasOne("Examination_System_Web_App.Models.Department", "dept_noNavigation")
                        .WithMany("Dept_inst_courses")
                        .HasForeignKey("dept_no")
                        .IsRequired()
                        .HasConstraintName("FK__Dept_inst__dept___0EF836A4");

                    b.HasOne("Examination_System_Web_App.Models.Instructor", "inst")
                        .WithMany("Dept_inst_courses")
                        .HasForeignKey("inst_id")
                        .IsRequired()
                        .HasConstraintName("FK__Dept_inst__inst___0FEC5ADD");

                    b.Navigation("crs");

                    b.Navigation("dept_noNavigation");

                    b.Navigation("inst");
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Exam", b =>
                {
                    b.HasOne("Examination_System_Web_App.Models.Course", "crs")
                        .WithMany("Exams")
                        .HasForeignKey("crs_id")
                        .HasConstraintName("FK__Exam__crs_id__778AC167");

                    b.HasOne("Examination_System_Web_App.Models.Department", "dept_noNavigation")
                        .WithMany("Exams")
                        .HasForeignKey("dept_no")
                        .HasConstraintName("FK__Exam__dept_no__0C1BC9F9");

                    b.Navigation("crs");

                    b.Navigation("dept_noNavigation");
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Question", b =>
                {
                    b.HasOne("Examination_System_Web_App.Models.Course", "crs")
                        .WithMany("Questions")
                        .HasForeignKey("crs_id")
                        .HasConstraintName("FK__Question__crs_id__7A672E12");

                    b.Navigation("crs");
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Std_course", b =>
                {
                    b.HasOne("Examination_System_Web_App.Models.Course", "crs")
                        .WithMany("Std_courses")
                        .HasForeignKey("crs_id")
                        .IsRequired()
                        .HasConstraintName("fk_std_course_crs_id");

                    b.HasOne("Examination_System_Web_App.Models.Student", "std")
                        .WithMany("Std_courses")
                        .HasForeignKey("std_id")
                        .IsRequired()
                        .HasConstraintName("fk_std_course_std_id");

                    b.Navigation("crs");

                    b.Navigation("std");
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Student", b =>
                {
                    b.HasOne("Examination_System_Web_App.Models.Department", "dept_noNavigation")
                        .WithMany("Students")
                        .HasForeignKey("dept_no")
                        .HasConstraintName("FK__Student__dept_no__6A30C649");

                    b.Navigation("dept_noNavigation");
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Student_answer", b =>
                {
                    b.HasOne("Examination_System_Web_App.Models.Exam", "exam")
                        .WithMany("Student_answers")
                        .HasForeignKey("exam_id")
                        .IsRequired()
                        .HasConstraintName("FK__Student_a__exam___04E4BC85");

                    b.HasOne("Examination_System_Web_App.Models.Question", "q_idNavigation")
                        .WithMany("Student_answers")
                        .HasForeignKey("q_id")
                        .IsRequired()
                        .HasConstraintName("FK__Student_an__q_id__05D8E0BE");

                    b.HasOne("Examination_System_Web_App.Models.Student", "std")
                        .WithMany("Student_answers")
                        .HasForeignKey("std_id")
                        .IsRequired()
                        .HasConstraintName("FK__Student_a__std_i__03F0984C");

                    b.Navigation("exam");

                    b.Navigation("q_idNavigation");

                    b.Navigation("std");
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Topic", b =>
                {
                    b.HasOne("Examination_System_Web_App.Models.Course", "crs")
                        .WithMany("Topics")
                        .HasForeignKey("crs_id")
                        .HasConstraintName("FK__Topic__crs_id__6754599E");

                    b.Navigation("crs");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("Examination_System_Web_App.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Examination_System_Web_App.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Course", b =>
                {
                    b.Navigation("Dept_inst_courses");

                    b.Navigation("Exams");

                    b.Navigation("Questions");

                    b.Navigation("Std_courses");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Department", b =>
                {
                    b.Navigation("Dept_inst_courses");

                    b.Navigation("Exams");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Exam", b =>
                {
                    b.Navigation("Student_answers");
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Instructor", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Dept_inst_courses");
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Question", b =>
                {
                    b.Navigation("Choices");

                    b.Navigation("Student_answers");
                });

            modelBuilder.Entity("Examination_System_Web_App.Models.Student", b =>
                {
                    b.Navigation("Std_courses");

                    b.Navigation("Student_answers");
                });
#pragma warning restore 612, 618
        }
    }
}
